### ISSUE TITLE
When filter in production code is specified the callback is null

### ISSUE THREAD

**Issue by stany9g** [kristofberge/EventAggregator_Mocker#9]
Hello,

when `eventAggregator.GetEvent<SomeEvent>().Subscribe(SetSth, airports => sth.Id == Id);` is in the production code, than the 
`eventAggregator.RegisterNewMockedEvent<SomeEvent, Args>().SetSubscribeCallback(action => callBack = action, filter: It.IsAny<Predicate<Args>>());` (also without explicitly stating the filter predicate) does not work and after creating the production class a callback is still null.

I tested it, that the problem is caused by the filter because when I remove it from production code a callBack is set right.

Do you have any suggestions on how to handle this scenario?

Thank you.
Stany.

**Comment by kristofberge** [comment]
Hello @stany9g,

Thanks for bringing this to my attention. I haven't been able to do any programming for several weeks, because of an injury, so I'm sorry for the late reply. I'll have a look in the coming days to see if I can find a solution or workaround.

Have you been able to find anything else in the meanwhile?

Thanks,
Kristof

**Comment by stany9g** [comment]
Hi @kristofberge ,

I developed my own generic method for registering new mock without using the library.

Stanislav.

**Comment by wowfood** [comment]
I know this has been closed, but I'm now running into a similar issue.

@stany9g how did you resolve this issue?
